# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_stages: [commit, push]
default_language_version:
    python: python3
repos:
-   repo: local
    hooks:
    -   id: black
        name: run code formatter black
        stages: [commit]
        language: system
        entry: poetry run black patterns/
        types: [python]

    -   id: isort
        name: sort imports with isort
        entry: poetry run isort
        language: system
        types: [python]

    -   id: pylint
        name: run pylint
        stages: [commit]
        language: system
        entry: poetry run pylint
        types: [python]
        exclude: tests/

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: fix-byte-order-marker
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-toml
    -   id: check-added-large-files
minimum_pre_commit_version: '2'
